"""Add storage audit and deduplication tables

Revision ID: b1a2c3d4e5f6
Revises: ca4653c80b38
Create Date: 2025-11-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a2c3d4e5f6'
down_revision = 'ca4653c80b38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create storage_audit table
    op.create_table('storage_audit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('operation', sa.String(length=50), nullable=False),
        sa.Column('operation_status', sa.String(length=20), nullable=False),
        sa.Column('user_id', sa.String(length=100), nullable=True),
        sa.Column('session_id', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('content_type', sa.String(length=100), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_audit_file_hash', 'storage_audit', ['file_hash'], unique=False)
    op.create_index('ix_storage_audit_file_path', 'storage_audit', ['file_path'], unique=False)
    op.create_index('ix_storage_audit_operation', 'storage_audit', ['operation'], unique=False)
    op.create_index('ix_storage_audit_created_at', 'storage_audit', ['created_at'], unique=False)

    # Create file_deduplication table
    op.create_table('file_deduplication',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('original_filename', sa.String(length=255), nullable=False),
        sa.Column('stored_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(length=100), nullable=True),
        sa.Column('reference_count', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_compressed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('compression_type', sa.String(length=20), nullable=True),
        sa.Column('original_size', sa.Integer(), nullable=True),
        sa.Column('compressed_size', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_hash'),
        sa.UniqueConstraint('stored_path')
    )
    op.create_index('ix_file_deduplication_file_hash', 'file_deduplication', ['file_hash'], unique=False)
    op.create_index('ix_file_deduplication_last_accessed', 'file_deduplication', ['last_accessed'], unique=False)

    # Create file_access_control table
    op.create_table('file_access_control',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('access_level', sa.String(length=20), nullable=False),
        sa.Column('allowed_users', sa.Text(), nullable=True),
        sa.Column('allowed_roles', sa.Text(), nullable=True),
        sa.Column('access_rules', sa.Text(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_access_control_file_path', 'file_access_control', ['file_path'], unique=False)
    op.create_index('ix_file_access_control_file_hash', 'file_access_control', ['file_hash'], unique=False)
    op.create_index('ix_file_access_control_access_level', 'file_access_control', ['access_level'], unique=False)
    op.create_index('ix_file_access_control_expires_at', 'file_access_control', ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_access_control_expires_at', 'file_access_control')
    op.drop_index('ix_file_access_control_access_level', 'file_access_control')
    op.drop_index('ix_file_access_control_file_hash', 'file_access_control')
    op.drop_index('ix_file_access_control_file_path', 'file_access_control')
    op.drop_table('file_access_control')
    op.drop_index('ix_file_deduplication_last_accessed', 'file_deduplication')
    op.drop_index('ix_file_deduplication_file_hash', 'file_deduplication')
    op.drop_table('file_deduplication')
    op.drop_index('ix_storage_audit_created_at', 'storage_audit')
    op.drop_index('ix_storage_audit_operation', 'storage_audit')
    op.drop_index('ix_storage_audit_file_path', 'storage_audit')
    op.drop_index('ix_storage_audit_file_hash', 'storage_audit')
    op.drop_table('storage_audit')
    # ### end Alembic commands ###