"""Initial migration for AP Intake database

Revision ID: ca4653c80b38
Revises:
Create Date: 2025-11-06 10:52:25.389872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ca4653c80b38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create base_uuid_mixin table first
    op.create_table('base_uuid_mixin',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='vendorstatus'), nullable=False),
    sa.Column('payment_terms_days', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.String(length=20), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("CASE WHEN email IS NOT NULL THEN email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' ELSE true END", name='check_email_format'),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='check_currency_format'),
    sa.CheckConstraint("name <> ''", name='check_vendor_name_not_empty'),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index('idx_vendor_active_status', 'vendors', ['active', 'status'], unique=False)
    op.create_index('idx_vendor_name_active', 'vendors', ['name', 'active'], unique=False)
    op.create_index(op.f('ix_vendors_active'), 'vendors', ['active'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)

    op.create_table('invoices',
    sa.Column('vendor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PARSED', 'VALIDATED', 'EXCEPTION', 'READY', 'STAGED', 'DONE', name='invoicestatus'), nullable=False),
    sa.Column('workflow_state', sa.String(length=50), nullable=True),
    sa.Column('workflow_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_name <> ''", name='check_file_name_not_empty'),
    sa.CheckConstraint("file_size <> ''", name='check_file_size_not_empty'),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_created_status', 'invoices', ['created_at', 'status'], unique=False)
    op.create_index('idx_vendor_status', 'invoices', ['vendor_id', 'status'], unique=False)
    op.create_index('idx_workflow_status', 'invoices', ['workflow_state', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_file_hash'), 'invoices', ['file_hash'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_invoices_workflow_state'), 'invoices', ['workflow_state'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('po_no', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lines_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_amount', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIAL', 'RECEIVED', 'CLOSED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='check_po_currency_format'),
    sa.CheckConstraint("po_no <> ''", name='check_po_no_not_empty'),
    sa.CheckConstraint("total_amount <> ''", name='check_total_amount_not_empty'),
    sa.CheckConstraint('expected_date IS NULL OR expected_date >= order_date', name='check_expected_date_after_order'),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_po_expected_date', 'purchase_orders', ['expected_date'], unique=False)
    op.create_index('idx_po_status_date', 'purchase_orders', ['status', 'order_date'], unique=False)
    op.create_index('idx_po_vendor_status', 'purchase_orders', ['vendor_id', 'status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)

    op.create_table('exceptions',
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('details_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_reason_code'), 'exceptions', ['reason_code'], unique=False)

    op.create_table('goods_receipt_notes',
    sa.Column('grn_no', sa.String(length=100), nullable=False),
    sa.Column('po_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lines_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('tracking_no', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("grn_no <> ''", name='check_grn_no_not_empty'),
    sa.CheckConstraint("received_by <> ''", name='check_received_by_not_empty'),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_grn_carrier', 'goods_receipt_notes', ['carrier'], unique=False)
    op.create_index('idx_grn_po_received', 'goods_receipt_notes', ['po_id', 'received_at'], unique=False)
    op.create_index('idx_grn_received_date', 'goods_receipt_notes', ['received_at'], unique=False)
    op.create_index(op.f('ix_goods_receipt_notes_grn_no'), 'goods_receipt_notes', ['grn_no'], unique=True)

    op.create_table('invoice_extractions',
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('header_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('lines_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.String(length=20), nullable=True),
    sa.Column('page_count', sa.String(length=10), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.create_table('staged_exports',
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('payload_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('format', sa.Enum('CSV', 'JSON', name='exportformat'), nullable=False),
    sa.Column('status', sa.Enum('PREPARED', 'SENT', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('export_job_id', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )

    op.create_table('validations',
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_version', sa.String(length=50), nullable=False),
    sa.Column('validator_version', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.String(length=20), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base_uuid_mixin.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_validations_passed'), 'validations', ['passed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validations_passed'), table_name='validations')
    op.drop_table('validations')
    op.drop_table('staged_exports')
    op.drop_table('invoice_extractions')
    op.drop_index(op.f('ix_goods_receipt_notes_grn_no'), table_name='goods_receipt_notes')
    op.drop_index('idx_grn_received_date', table_name='goods_receipt_notes')
    op.drop_index('idx_grn_po_received', table_name='goods_receipt_notes')
    op.drop_index('idx_grn_carrier', table_name='goods_receipt_notes')
    op.drop_table('goods_receipt_notes')
    op.drop_index(op.f('ix_exceptions_reason_code'), 'exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_index('idx_po_vendor_status', table_name='purchase_orders')
    op.drop_index('idx_po_status_date', table_name='purchase_orders')
    op.drop_index('idx_po_expected_date', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_invoices_workflow_state'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_file_hash'), table_name='invoices')
    op.drop_index('idx_workflow_status', table_name='invoices')
    op.drop_index('idx_vendor_status', table_name='invoices')
    op.drop_index('idx_created_status', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_active'), table_name='vendors')
    op.drop_index('idx_vendor_name_active', table_name='vendors')
    op.drop_index('idx_vendor_active_status', table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('base_uuid_mixin')
    # ### end Alembic commands ###